name: tests

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"
      - run: npm install --include=dev
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
